### Site Settings ###
title               : Haziq's Portfolio
description         : >-
                      Data for good, Data for Insights :coffee:,
                      Love my codes to be clean and useful :heart:.
                      Accepted the fact that most data are messy.
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : ameerhaziq20/ameerhaziq20.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md

### Author Info ###
author:
  name              : Ameer Haziq Basharuddin
  image             : https://pbs.twimg.com/profile_images/1382763560019718147/ZqCfSczE_400x400.jpg
# behance           : your_username
# dribbble          : your_username
  email             : ameerhaziq.work@gmail.com
# facebook          : your_username
  github            : ameerhaziq20
# gitlab            : your_username
  instagram         : emyrbreezy
# kaggle            : your_username
  linkedin          : ameer-haziq-basharuddin-89593520a/
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : frisk__y
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name

  resume:
    output: true
    permalink: /resume

### Disqus ###
disqus:
  shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: true                                        # Set true to enable analytics
  google:
    tracking_id: G-L9THXNRT78


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"

